vich_uploader:
    db_driver: orm

    mappings:
        media:
            uri_prefix: /uploads/medias
            upload_destination: '%kernel.project_dir%/public/uploads/medias'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
